# -*- coding: utf-8 -*-
"""EV Market Segment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBAB9HWG3OY5ccvy7MkBXnG5yUQWxgI7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/Electric_Vehicle_Survey.csv')

#Function to display column names and first few rows of the dataset
def explore_dataset(df):
    print("Column Names:")
    print(df.columns)
    print("\nFirst few rows of the dataset:")
    print(df.head())

# Function to visualize pair relationships and distributions
def visualize_relationships(df, columns_of_interest):
    # Pairplot with hue based on EV preference
    sns.pairplot(df[columns_of_interest], hue='What kind of Electric Vehicle do you want?', corner=True, diag_kind='kde')
    plt.suptitle('Pairplot of Age, Annual Income, Area of Living, and State / UT by EV Preference', y=1.02)
    plt.show()

    # Boxplot of income distribution across areas of living by EV preference
    plt.figure(figsize=(10, 6))
    sns.boxplot(x='Area of Living', y='Approx. Annual Income', hue='What kind of Electric Vehicle do you want?', data=df)
    plt.title('Income Distribution across Area of Living by EV Preference')
    plt.xticks(rotation=45)
    plt.show()

    # Age distribution by state/UT and EV preference
    plt.figure(figsize=(10, 6))
    sns.histplot(data=df, x='Age', hue='What kind of Electric Vehicle do you want?', multiple='stack', bins=30, kde=True)
    plt.title('Age Distribution by State / UT and EV Preference')
    plt.xlabel('Age')
    plt.show()

    # Count of vehicle preferences
    plt.figure(figsize=(10, 6))
    vehicle_counts = df['What kind of Electric Vehicle do you want?'].value_counts()
    sns.barplot(x=vehicle_counts.index, y=vehicle_counts.values)
    plt.title('Electric Vehicle Preference')
    plt.xlabel('EV Type')
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    plt.show()

# Function to summarize insights and formulate targeting strategy
def summarize_and_recommend(df):
    # Print summary statistics or insights derived from analysis
    print("\nSummary of Insights:")
    print("-" * 50)
    print("1. Vehicle Preferences:")
    print(df['What kind of Electric Vehicle do you want?'].value_counts())
    print("\n2. Income Distribution across Areas of Living:")
    print(df.groupby('Area of Living')['Approx. Annual Income'].describe())
    print("\n3. Age Distribution by State / UT:")
    print(df.groupby('State / UT')['Age'].describe())

    # Formulate targeting strategy based on insights
    print("\nRecommendations for Targeting Strategy:")
    print("-" * 50)
    print("Based on the analysis, focus marketing efforts on:")
    print("- Demographics preferring specific types of EVs.")
    print("- Areas with higher income levels interested in EVs.")
    print("- Age groups and regions showing openness to EV adoption.")

# Main execution flow
if __name__ == "__main__":
    explore_dataset(df)

    columns_of_interest = ['Age', 'Approx. Annual Income', 'Area of Living', 'State / UT',
                           'Which vehicles do you prefer?', 'Are you willing to switch from Combustions Vehicles to EV?',
                           'What kind of Electric Vehicle do you want?', 'Budget']

    visualize_relationships(df, columns_of_interest)
    summarize_and_recommend(df)